insert into doctor values (1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Kuznetsov', 'Mykyta', 'Victorovich' , 'DENTIST');
insert into doctor values (2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Sidorov', 'Ivan', 'Aleksandrovich' , 'DENTIST');
insert into doctor values (3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Petrova', 'Sofia', 'Vyacheslavovna' , 'PEDIATRICIAN');
insert into doctor values (4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Ivanov', 'Petr', 'Vasilyevich' , 'SURGEON');
insert into doctor values (5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Petrenko', 'Dmitrii', 'Victorovich' , 'SURGEON');
insert into doctor values (6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Kunaev', 'Eugeni', 'Vasilyevich' , 'PEDIATRICIAN');
insert into doctor values (7, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Shatska', 'Elina', 'Mikhaylovna' , 'PHYSICIAN');
insert into doctor values (8, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Bovchaluk', 'Stanicslav', 'Yaroslavovich' , 'PHYSICIAN');
insert into doctor values (9, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Dinovich', 'Mykyta', 'Vladimirovich' , 'PEDIATRICIAN');
insert into doctor values (10, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Makashvilli', 'Arsen', 'Timurovich' , 'CARDIOLOGIST');
insert into doctor values (11, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Prakiv', 'Dmitrii', 'Stepanovich' , 'SURGEON');
insert into doctor values (12, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Divakov', 'Ivan', 'Petrovich' , 'SURGEON');


insert into patient values (1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Antonenko', 'Mykyta', 15);
insert into patient values (2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Bondarenko', 'Vadym', 25);
insert into patient values (3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Burtseva', 'Kateryna', 17);
insert into patient values (4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Hunchenko', 'Artem', 20);
insert into patient values (5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Davydov', 'Oleksandr', 21);
insert into patient values (6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Dasiv', 'Eduard', 19);
insert into patient values (7, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Dovhalin', 'Denys', 22);
insert into patient values (8, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Klen', 'Iryna', 21);
insert into patient values (9, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Kulyk', 'Nataliia', 24);
insert into patient values (10, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Lobanov', 'Kyrylo', 17);
insert into patient values (11, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Makhotka', 'Andrii', 23);
insert into patient values (12, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Mohylevska', 'Anastasiia', 18);
insert into patient values (13, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Mulika', 'Yaroslav', 29);
insert into patient values (14, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Panchenko', 'Yelisei', 20);
insert into patient values (15, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Pohorielova', 'Liliia', 18);
insert into patient values (16, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Poliakov', 'Vladyslav', 21);
insert into patient values (17, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Svistelnyk', 'Daniil', 23);
insert into patient values (18, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Suvorova', 'Anastasiia', 24);
insert into patient values (19, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Tverdokhlib', 'Daniil', 22);
insert into patient values (20, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Cherednychenko', 'Ihor', 18);
insert into patient values (21, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Shakirov', 'Yehor', 20);


insert into declaration values (1, 1, 1);
insert into declaration values (2, 1, 5);
insert into declaration values (3, 1, 10);
insert into declaration values (4, 1, 15);
insert into declaration values (5, 2, 6);
insert into declaration values (6, 2, 11);
insert into declaration values (7, 2, 16);
insert into declaration values (8, 3, 7);
insert into declaration values (9, 3, 12);
insert into declaration values (10, 3, 17);
insert into declaration values (11, 4, 14);
insert into declaration values (12, 5, 5);
insert into declaration values (13, 5, 15);
insert into declaration values (14, 5, 18);
insert into declaration values (15, 5, 16);
insert into declaration values (16, 6, 7);
insert into declaration values (17, 6, 17);
insert into declaration values (18, 6, 20);
insert into declaration values (19, 7, 6);
insert into declaration values (20, 7, 12);
insert into declaration values (21, 7, 17);
insert into declaration values (22, 8, 2);
insert into declaration values (23, 8, 10);
insert into declaration values (24, 8, 20);
insert into declaration values (25, 9, 8);
insert into declaration values (26, 9, 14);
insert into declaration values (27, 9, 18);
insert into declaration values (28, 10, 8);
insert into declaration values (29, 10, 16);
insert into declaration values (30, 10, 19);
insert into declaration values (31, 11, 12);
insert into declaration values (32, 11, 21);
insert into declaration values (33, 11, 8);
insert into declaration values (34, 12, 20);
insert into declaration values (35, 12, 21);